version: '2.1'

services:
  mysql-test:
    image: mysql:5.6
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    expose:
      - 3306
    hostname: mysql-test
    ports:
      - "3306:3306"
