// Code generated by Exodus [https://github.com/tmus/exodus]. DO NOT EDIT.

package main

import (
	"os"

	"github.com/tmus/exodus"
	"github.com/tmus/exodus/driver"
)

var migrations []exodus.Migration = []exodus.Migration{
	migration20220115115948create_users_table{},
} // END OF MIGRATIONS

func main() {
	driver, err := driver.NewMysqlDriver("root:root@/db")
	if err != nil {
		panic(err)
	}
	defer driver.Close()

	migrator, err := exodus.NewMigrator(driver)
	if err != nil {
		panic(err)
	}

	if err := migrator.Run(os.Args[1], migrations...); err != nil {
		panic(err)
	}
}
