// Code generated by Exodus [https://github.com/tmus/exodus]. DO NOT EDIT.

package main

import (
	"database/sql"

	_ "github.com/mattn/go-sqlite3"
	"github.com/tmus/exodus"
)

var migrations []exodus.Migration = []exodus.Migration{
	migration20220115115948create_users_table{},
} // END OF MIGRATIONS

func main() {
	db, err := sql.Open("sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	migrator, err := exodus.NewMigrator(db)
	if err != nil {
		panic(err)
	}

	if err := migrator.Run(migrations...); err != nil {
		panic(err)
	}
}
